"""
Main Interface for AI Code Generator and Evaluator
Prototype for industry-usable AI code generation assistant
"""

import os
import sys
from typing import Optional
from code_generator import CodeGenerator
from code_evaluator import CodeBLEUEvaluator

# Try to load from .env file if available
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv is optional


class AICodeAssistant:
    """
    Main interface combining code generation and evaluation.
    """
    
    def __init__(self, api_key: Optional[str] = None, model: str = "codestral-latest"):
        """
        Initialize the AI Code Assistant.
        
        Args:
            api_key: Mistral API key (or set MISTRAL_API_KEY environment variable)
            model: Model to use for code generation (default: codestral-latest)
        """
        self.generator = CodeGenerator(api_key=api_key, model=model)
        self.evaluator = CodeBLEUEvaluator()
    
    def generate(self, query: str, language: Optional[str] = None) -> str:
        """
        Generate code based on user query.
        Returns ONLY code, no explanations.
        
        Args:
            query: User's code generation request
            language: Target programming language
        
        Returns:
            Generated code string
        """
        return self.generator.generate_code(query, language)
    
    def evaluate(self, generated_code: str, reference_code: str, 
                language: str = "python") -> dict:
        """
        Evaluate generated code against reference code.
        
        Args:
            generated_code: Code generated by the agent
            reference_code: Correct/reference code
            language: Programming language
        
        Returns:
            Evaluation results dictionary
        """
        return self.evaluator.evaluate(generated_code, reference_code, language)
    
    def generate_and_evaluate(self, query: str, reference_code: str,
                             language: Optional[str] = None) -> dict:
        """
        Generate code and evaluate it in one step.
        
        Args:
            query: User's code generation request
            reference_code: Correct/reference code for evaluation
            language: Target programming language
        
        Returns:
            Dictionary with generated code and evaluation results
        """
        generated_code = self.generate(query, language)
        evaluation = self.evaluate(generated_code, reference_code, 
                                   language or "python")
        
        return {
            "generated_code": generated_code,
            "evaluation": evaluation
        }


def main():
    """
    Command-line interface for the AI Code Assistant.
    """
    import argparse
    
    parser = argparse.ArgumentParser(
        description="AI Code Generator and Evaluator - Industry Prototype"
    )
    parser.add_argument(
        "query",
        help="Code generation query"
    )
    parser.add_argument(
        "--language", "-l",
        help="Target programming language (python, cpp, java, etc.)",
        default=None
    )
    parser.add_argument(
        "--evaluate", "-e",
        help="Reference code file to evaluate against",
        default=None
    )
    parser.add_argument(
        "--output", "-o",
        help="Output file to save generated code",
        default=None
    )
    parser.add_argument(
        "--api-key",
        help="Mistral API key (or set MISTRAL_API_KEY env var)",
        default=None
    )
    parser.add_argument(
        "--model",
        help="Model to use for generation (codestral-latest, codestral-mamba-latest)",
        default="codestral-latest"
    )
    
    args = parser.parse_args()
    
    # Initialize assistant
    api_key = args.api_key or os.getenv("MISTRAL_API_KEY")
    if not api_key:
        print("Error: Mistral API key required. Set MISTRAL_API_KEY env var or use --api-key")
        print("Get your API key from: https://console.mistral.ai/")
        sys.exit(1)
    
    assistant = AICodeAssistant(api_key=api_key, model=args.model)
    
    # Generate code
    try:
        generated_code = assistant.generate(args.query, args.language)
        
        # Output only code (as per requirements)
        print(generated_code)
        
        # Save to file if requested
        if args.output:
            with open(args.output, 'w', encoding='utf-8') as f:
                f.write(generated_code)
            print(f"\nCode saved to {args.output}", file=sys.stderr)
        
        # Evaluate if reference code provided
        if args.evaluate:
            with open(args.evaluate, 'r', encoding='utf-8') as f:
                reference_code = f.read()
            
            evaluation = assistant.evaluate(
                generated_code,
                reference_code,
                args.language or "python"
            )
            
            report = assistant.evaluator.get_evaluation_report(
                generated_code,
                reference_code,
                args.language or "python"
            )
            print(report, file=sys.stderr)
    
    except Exception as e:
        print(f"Error: {str(e)}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()

